embed_dim: 64
learning_rate: 0.001
batch_size: 2048
eval_batch_size: 128
epochs: 1000
early_stop_patience: 100
cutoff: [20, 10, 5]
split_ratio: [0.8, 0.1, 0.1]


l2_reg_weight: 1e-4
n_layers: 3
eps: 0.1
cl_neg_type: all
cl_weight: 0.5
temperature: 0.2